# Generated by Django 3.0.8 on 2020-07-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsible',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
